apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent.yaml
images:
  - name: 729231827726.dkr.ecr.us-east-2.amazonaws.com/dev/voyago
    newTag: agent-916ad5de786e578f0b569a161c63d23b57febce9