apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent.yaml
images:
  - name: 729231827726.dkr.ecr.us-east-2.amazonaws.com/dev/voyago
    newTag: agent-0d4ca8fb8d1252e01f0ee348be497464f55b721f
